spring:
  application:
    name: demo
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate  # 스키마는 SQL로 직접 만들고, JPA는 매핑만 검증
      open-in-view: false   # 트랜잭션 밖 지연로딩 방지 (권장)
      show-sql: true
      properties:
        hibernate.format_sql: true
